# Generated by Django 5.0.4 on 2024-05-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
