# Generated by Django 5.0.4 on 2024-05-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0002_alter_category_created_at_alter_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_status',
            field=models.CharField(default='True', max_length=200),
        ),
    ]
