# Generated by Django 5.0.4 on 2024-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=200)),
                ('tax_per', models.CharField(max_length=200)),
                ('tax_status', models.CharField(max_length=200)),
            ],
        ),
    ]
