# Generated by Django 5.0.4 on 2024-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0005_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.IntegerField()),
                ('subcategory_Name', models.CharField(max_length=200)),
                ('subcategory_img', models.ImageField(upload_to='img')),
                ('subcategory_code', models.IntegerField()),
                ('subcategory_status', models.CharField(max_length=200)),
            ],
        ),
    ]
