# Generated by Django 5.0.4 on 2024-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0008_alter_brand_brand_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_status', models.CharField(default='True', max_length=200)),
            ],
        ),
    ]
