# Generated by Django 5.0.4 on 2024-05-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0009_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('state_status', models.CharField(default='True', max_length=200)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineapp.country')),
            ],
        ),
    ]
