# Generated by Django 5.0.4 on 2024-05-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0010_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_status', models.CharField(default='True', max_length=200)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineapp.state')),
            ],
        ),
    ]
