# Generated by Django 5.0.4 on 2024-05-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0011_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_number', models.IntegerField()),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_image', models.ImageField(upload_to='categoryimage')),
                ('customer_wpnumber', models.IntegerField()),
                ('customer_Address', models.CharField(max_length=200)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineapp.city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineapp.country')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineapp.state')),
            ],
        ),
    ]
